### ISSUE TITLE
Add support for variable parts of the version in URLs

### ISSUE THREAD

**Issue by blaix** [gren-lang/package.gren-lang.org#39]
Allow links like `https://packages.gren-lang.org/package/blaix/gren-ansi/version/1.x.x/overview` where `1.x.x` would route to the latest published version that is `< 2.0.0`.

This lets you write documentation with forward-compatible links. For example,  gren-tui currently depends on gren-ansi version 1.0.0, but thanks to gren's enforced semantic versioning, it should be forward compatible with all 1.x versions, so ideally I could put links in the gren-tui docs that always go to the latest 1.x version of the gren-ansi docs. But currently my options are `latest` which could go to an incompatible version in the future, or hard-code a link that could become outdated.

**Comment by robinheghan** [comment]
Would `1` and `1.5` be ok, or do you prefer `1.x.x` and `1.5.x`?

**Comment by robinheghan** [comment]
Haven't yet decided what I'd prefer, so just looking for feedback

**Comment by blaix** [comment]
I have no preference. Whichever is easier to implement :)
